### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by AlSarsawi** [ForumHulp/htmlemail#11]
Hello

can you please guide me step by step how can i use this ext.
i enable it .. and go to includes/functions_messenger.php
and in line 209 / function set_mail_html($html = false)
change it to true .. function set_mail_html($html = true)

is this correct ??

and then i must go to /language/en/email
and change .txt files contents with html codes

i tried this steps but didn't work with me
i use phpbb 3.2

**Comment by Galixte** [comment]
Hi @ForumHulp,

could you take a look, please ?

**Comment by ForumHulp** [comment]
No that's not the way.

The script which is calling messenger should be used.
Example:
$messenger = new \messenger(false);
$messenger->set_mail_html(true);
$messenger->template('@forumhulp_classifieds/webshop.html', 'en');
etc

**Comment by AlSarsawi** [comment]
Hi

Sorry for asking this again, I didn't use the Ext. at that time but now I need it

I still didn't get it because I am not a developer
I want to use this Ext. for the regular phpBB emails (user welcome, topic or post notify, ... )

So what I must change exactly because I tried a lot
Can you please guide me with "find and replace" instructions

Thank you for your time

**Comment by Galixte** [comment]
Hi @ForumHulp,

could you take a look, please ?

**Comment by ForumHulp** [comment]
Like I told in above message:
search in scripts where messenger is called. 
Add line set_mail(true) and eventual a template file.
Clear cache

**Comment by AlSarsawi** [comment]
issue solved finally
I just changed "false" to "true" in lines 32, 46, 209 !!

Thank you for your great work

**Comment by Galixte** [comment]
Okay:
- line 32: ```var $use_html = false;```
- Line 46: ```$this->use_html = false;```
- Line 209: ```function set_mail_html($html = false)```

All of these have to be set to ```true```.

Thanks!

**Comment by AlSarsawi** [comment]
Hello

Sorry to open this again
not all emails now in html

for example
user welcome, user activate passwd, contact admin in html

but
new topic or post or private message still in text

Is there's something I miss and need to edit ?

Thank you

**Comment by ForumHulp** [comment]
As i already told you have to setup messenger:
$messenger = new \messenger(false);
$messenger->set_mail_html(true);
$messenger->template('@forumhulp_classifieds/webshop.html', 'en');
or change the called email template to your html

**Comment by Galixte** [comment]
@AlSarsawi I will test it and report the full method. @ForumHulp I hoped you will write it but I can do that.

**Comment by AlSarsawi** [comment]
I just added
`$messenger->set_mail_html(true);`
to /phpbb/notification/method/messenger_base.php

before
`$messenger->template($notification->get_email_template(), $user['user_lang'], '', $template_dir_prefix);`

and I test "new topic" and "new private message" and it's in html
I hope all emails now in html but it need to test it all

**Comment by tanzanian** [comment]
> @AlSarsawi I will test it and report the full method. @ForumHulp I hoped you will write it but I can do that.

Hi Galixte
Did you manage to write the full instructions of which elements in which files need to be changed?
We are trying to implement the ext and a list of files that need to be edited and the line numbers that need to be edited would go a long way in making this friendly for php newbies.

**Comment by Galixte** [comment]
> > @AlSarsawi I will test it and report the full method. @ForumHulp I hoped you will write it but I can do that.
> 
> Hi Galixte
> Did you manage to write the full instructions of which elements in which files need to be changed?
> We are trying to implement the ext and a list of files that need to be edited and the line numbers that need to be edited would go a long way in making this friendly for php newbies.

@tanzanian have a look here: http://www.ezcom-fr.com/viewtopic.php?p=4467#p4467 & http://www.ezcom-fr.com/viewtopic.php?p=4618#p4618.
