### ISSUE TITLE
Error 500 when activating/enabling the extension in the ACP

### ISSUE THREAD

**Issue by ErikThiart** [ForumHulp/htmlemail#12]
I am on version 3.2.*

![chrome_2017-11-27_22-34-25](https://user-images.githubusercontent.com/9626641/33288131-d7bf53b2-d3c3-11e7-8c65-0ae58ef08d40.png)

Results in
![chrome_2017-11-27_22-33-46](https://user-images.githubusercontent.com/9626641/33288172-fdca4c1a-d3c3-11e7-88dd-3fcd5cb9edca.png)

**Comment by ForumHulp** [comment]
Hi Erik

 

I installed it again on my testboard without problems.

Can you send me more information?

 

Greetz

 

 <http://forumhulp.com/> 
Webhosting, Custom MODs, Technisch beheer, MOD installaties, Webdesign  en website ontwikkeling

 

 

 

 

Van: Erik Thiart [mailto:notifications@github.com] 
Verzonden: maandag 27 november 2017 21:41
Aan: ForumHulp/htmlemail <htmlemail@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ForumHulp/htmlemail] Error 500 when activating/enabling the extension in the ACP (#12)

 

 <https://user-images.githubusercontent.com/9626641/33288131-d7bf53b2-d3c3-11e7-8c65-0ae58ef08d40.png> 

Results in
 <https://user-images.githubusercontent.com/9626641/33288172-fdca4c1a-d3c3-11e7-88dd-3fcd5cb9edca.png>

**Comment by ErikThiart** [comment]
From your documentation, there is a critical part left out, under requirements, this plugin appears to be dependant on another plugin that must be installed first.

**Comment by ErikThiart** [comment]
I created a pull request with the updated documentation.
