### ISSUE TITLE
Edit in /includes/acp/acp_email.php stopped working

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [ForumHulp/htmlemail#15]
Hello,

I updated phpBB to 3.2.7. When sending an HTML mass mail I now get a white page. It was working in phpBB 3.2.5.

I placed:  $messenger->set_mail_html(true);
Right under:  $messenger = new messenger($use_queue);

This is the error log:

`[Thu May 09 18:06:07.037031 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method messenger::set_mail_html() in /var/www/vhosts/solidjeuh.be/httpdocs/includes/acp/acp_email.php:202, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email
[Thu May 09 18:06:07.037168 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: Stack trace:, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email
[Thu May 09 18:06:07.037192 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: #0 /var/www/vhosts/solidjeuh.be/httpdocs/includes/functions_module.php(676): acp_email->main('email', 'email'), referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email
[Thu May 09 18:06:07.037235 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: #1 /var/www/vhosts/solidjeuh.be/httpdocs/adm/index.php(82): p_master->load_active(), referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email
[Thu May 09 18:06:07.037267 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: #2 {main}, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email
[Thu May 09 18:06:07.037286 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr:   thrown in /var/www/vhosts/solidjeuh.be/httpdocs/includes/acp/acp_email.php on line 202, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email`

**Comment by ForumHulp** [comment]
Install it  again

 

 

Greetz

 

Van: Andy Dm <notifications@github.com> 
Verzonden: donderdag 9 mei 2019 18:15
Aan: ForumHulp/htmlemail <htmlemail@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ForumHulp/htmlemail] Edit is /includes/acp/acp_email.php stopped working (#15)

 

Hello,

I updated phpBB to 3.2.7. When sending an HTML mass mail I now get a white page. It was working in phpBB 3.2.5.

I places: $messenger->set_mail_html(true);
Right under: $messenger = new messenger($use_queue);

This is the error log:

[Thu May 09 18:06:07.037031 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to undefined method messenger::set_mail_html() in /var/www/vhosts/solidjeuh.be/httpdocs/includes/acp/acp_email.php:202, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email [Thu May 09 18:06:07.037168 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: Stack trace:, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email [Thu May 09 18:06:07.037192 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: #0 /var/www/vhosts/solidjeuh.be/httpdocs/includes/functions_module.php(676): acp_email->main('email', 'email'), referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email [Thu May 09 18:06:07.037235 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: #1 /var/www/vhosts/solidjeuh.be/httpdocs/adm/index.php(82): p_master->load_active(), referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email [Thu May 09 18:06:07.037267 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: #2 {main}, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email [Thu May 09 18:06:07.037286 2019] [fcgid:warn] [pid 4787:tid 139871943857920] [client 81.246.234.100:59652] mod_fcgid: stderr: thrown in /var/www/vhosts/solidjeuh.be/httpdocs/includes/acp/acp_email.php on line 202, referer: https://www.solidjeuh.be/adm/index.php?sid=ee5977775d75579bfeaf777f268fd4e0&i=acp_email&mode=email

**Comment by SpIdErPiGgY1984** [comment]
Oh so simple... lol. Thank you 😃
