### ISSUE TITLE
“However not all updates are done properly”

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/htmlemail#5]
Hi @ForumHulp,

the message: “However not all updates are done properly because of file permissions or missing files. See admin log for a overview.<br /><br />Please update files by hand to enjoy all functions !” makes me understand that i have to change the permission files in my FTP space (with the CHMOD commands 666).

In admin log is talking about (https://github.com/ForumHulp/htmlemail/issues/8) this file below hasn’t the correct permissions:  `/includes/functions_messenger.php`.

Which files ? The language files (*.txt) from phpBB vanilla or extension or both ?

When i read this: https://github.com/ForumHulp/emailonbirthday/blob/master/language/en/info_acp_emailonbirthday.php#L27, i understand that any e-mail file(s) (*.txt) in my forum (from phpBB vanilla or from an extension) will be send as HTML if i replace the text content with HTML content.

Am i in good way ?

And finally: “not all updates are done properly” of which updates the message talks about ?

**Comment by ForumHulp** [comment]
Hi Raphaël

The message is about functions_messenger. You should update it by hand it's telling or chmod so php can change it.

It's possible to send every message in html but you have to let messenger know it. Read succes message at enabling the extension

**Comment by Galixte** [comment]
Hi @ForumHulp,

how to do this: “but you have to let messenger know it.” ?

**Comment by Galixte** [comment]
Hi @ForumHulp,

any answer about my previous question, please ?

**Comment by ForumHulp** [comment]
$messenger->set_mail_html(true);
to let messenger know to output html and be sure you using a template with some html in it.
Example in emailonbirthday, look in cronfile It switches to emailonbirthday.txt in language/email

**Comment by Galixte** [comment]
Ok, without any extension, if i activate this extension, phpBB will send all emails in HTML ?
