### ISSUE TITLE
Messages don’t displayed correctly in Admin log

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/htmlemail#8]
Hi @ForumHulp,

after activated this extension, i have in Admin logs, this message:

```
{LOG CORE NOT UPDATED}
/includes/functions_messenger.php
```

instead of:

```
ForumHulp Core didn’t installed successfully
Could not update file(s)
» /includes/functions_messenger.php
```

And after delete data of this extension, i have this message in Admin logs:

```
{LOG CORE NOT REPLACED}
/includes/functions_messenger.php
```

instead of:

```
ForumHulp Core didn’t desinstalled successfully
Could not replaced file(s)
» /includes/functions_messenger.php
```

Could you fix this issue, please ?

**Comment by ForumHulp** [comment]
If extension is disabled it can not find the correct language variable anymore.
